routes/web.php
<?php

Route::middleware(['admin'])->namespace('Admin')->prefix('admin')->group(function() {
    Route::resource('news', 'NewsController');
    Route::resource('rubric', 'RubricController');
    Route::resource('users', 'UsersController');
    Route::resource('authors', 'AuthorController');
    Route::resource('shigarma', 'ShigarmalarController');
    Route::resource('orindaushi', 'OrindaushiController');
    Route::resource('nota', 'NotaController');
    Route::resource('olen', 'OlenderController');
    Route::resource('position', 'PositionController');
    Route::resource('menu', 'MenuController');
    Route::resource('pages', 'PageController');
    Route::resource('role', 'RoleController');
    Route::resource('archive', 'ArchiveController');
    Route::resource('banner', 'BannerController');
    Route::resource('slider', 'SliderController');
    Route::resource('subscription', 'SubscriptionController');
    Route::get('/', function () {
        return view('admin.index');
    });

});
Route::post('search', 'Admin\ShigarmalarController@search');


Route::get('lang/{locale}', 'LocalizationController@index');
Route::get('country/{locale}', 'LocalizationCountryController@index');

Route::middleware(['web'])->group(function() {
    Route::get('media/{file_name}', 'MediaController@getImage')->where('file_name', '.*');
    Route::get('media_avatar/{file_name}', 'MediaController@getAvatar')->where('file_name', '.*');
    Route::get('media_doc/{file_name}', 'MediaController@getFile')->where('file_name', '.*');
    Route::get('media_content/{file_name}', 'MediaController@getContentImage')->where('file_name', '.*');
    Route::post('content_image', 'MediaController@storeContentImage');
});

Route::get('/', 'IndexController@index');
Route::get('/category/{rubric_id}', 'CategoryController@getcategory');
Route::get('/shigarma/{shigarma_id}', 'CategoryController@getshigarma');
Route::get('/author/{author_id}', 'AuthorController@getauthorprofile');
Route::get('/orindaushi/{orindaushi_id}', 'AuthorController@getorindaushiprofile');

Auth::routes();
Route::get('/home', 'HomeController@index')->name('home');

app/Models/Rubric.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Rubric extends Model
{
    protected $primaryKey = 'rubric_id';
    protected $guarded = [];

    public function getPhotoAttribute($value){
        return url('/').$value;
    }
}

resources/views/authorprofile.blade.php
@extends('layouts.main')
@section('content')
    <section class="profile">

        <div class="container">
            <ol class="breadcrumb">
                <li><a href="/">Басты бет</a></li>
                <li class="active">{{$author->author_fio}}</li>
            </ol>
            <div class="row">
                <div class="col-md-3 col-sm-4">
                    <div class="profile-img">
                        <img src="{{$author->author_photo}}" alt="">
                    </div>
                </div>
                <div class="col-md-9 col-sm-8">
                    <div class="profile-caption">
                        <h1>{{$author->author_fio}}</h1>
                        {!! $author->author_description !!}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="category">
        <div class="container">
            <h2 class="subtitle">Шығармалар:</h2>
            <div class="row">
                @foreach($shigarmalar as $item)
                <div class="col-md-2 col-sm-3">
                    <div class="category-item">
                        <div class="category-item-img">
                            <img src="{{$item->photo}}" alt="">
                            <div class="overlay-play">
                                <div class="play-info">
                                    <img src="img/icon/play.png" alt="">
                                    <span>{{$item->duration}}</span>
                                </div>
                                <a href="/shigarma/{{$item->id}}" class="btn-plain play-lg">
                                    <img src="img/icon/play-lg.png" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="category-item-caption">
                            <h3>{{$item->name}}</h3>
                            @foreach($item->authors as $item)
                                <p>{{$item->author_fio}}</p>
                            @endforeach
                        </div>
                    </div>
                </div>
                @endforeach
            </div>
            {{$shigarmalar->links()}}
        </div>
    </section>
@endsection

resources/views/category.blade.php
@extends('layouts.main')
@section('content')
<section class="category">
    <div class="container">
        <h1>{{$rubric->rubric_name}}</h1>
        <ol class="breadcrumb">
            <li><a href="/">Басты бет</a></li>
            <li class="active">{{$rubric->rubric_name}}</li>
        </ol>
        <div class="row">
            @foreach($shigarmalar as $item)
            <div class="col-md-2 col-sm-3">
                <div class="category-item">
                    <div class="category-item-img">
                        <img src="{{$item->photo}}" alt="">
                        <div class="overlay-play">
                            <div class="play-info">
                                <img src="img/icon/play.png" alt="">
                                <span>{{$item->duration}}</span>
                            </div>
                            <a href="/shigarma/{{$item->id}}" class="btn-plain play-lg">
                                <img src="img/icon/play-lg.png" alt="">
                            </a>
                        </div>
                    </div>
                    <div class="category-item-caption">
                        <h3>{{$item->name}}</h3>
                        @foreach($item->authors as $item)
                            <p>{{$item->author_fio}}</p>
                        @endforeach
                    </div>
                </div>
            </div>
            @endforeach
        </div>
        {{ $shigarmalar->links() }}
    </div>
</section>
    @endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/index.blade.php
@extends('layouts.main')
@section('content')
    <section class="main">
        <div class="main-bg">
            <img src="{{$sliders[0]["slider_image"]}}" alt="">
        </div>
        <div class="container">
            <div class="main-caption">
                {{--<h1>{{$sliders[0]["header"]}}</h1>--}}
                <img src="/img/main/404.png" alt="">
            </div>
        </div>
    </section>
    <section class="type bg-grey">
        <div class="container">
            <div class="type-cover">
                <h2>Бөлімдер</h2>
                <div class="row">
                    @foreach($rubrics as $item)
                        <div class="col-md-4 col-sm-4">
                            <a href="/category/{{$item->rubric_id}}">
                                <div class="type-item">
                                    <div class="type-item-img">
                                        <img src="{{$item->photo}}" alt="">
                                    </div>
                                    <div class="type-item-caption">
                                        <h3>
                                            {{$item->rubric_name}}
                                        </h3>
                                    </div>
                                </div>
                            </a>
                        </div>
                    @endforeach
                </div>
            </div>
            <div class="description-base">
                <div class="row">
                    <div class="col-md-3 col-sm-4">
                        <div class="description-base-img">
                            <img src="img/main/logo-lg.png" alt="">
                        </div>
                    </div>
                    <div class="col-md-9 col-sm-8">
                        <div class="description-base-caption">
                            <h2>{{$sliders[1]["header"]}}</h2>
                            <p>
                                {{$sliders[1]["slider_text"]}}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection

resources/views/orindaushiprofile.blade.php
@extends('layouts.main')
@section('content')
    <section class="profile">

        <div class="container">
            <ol class="breadcrumb">
                <li><a href="/">Басты бет</a></li>
                <li class="active">{{$author->name}}</li>
            </ol>
            <div class="row">
                <div class="col-md-3 col-sm-4">
                    <div class="profile-img">
                        <img src="{{$author->photo}}" alt="">
                    </div>
                </div>
                <div class="col-md-9 col-sm-8">
                    <div class="profile-caption">
                        <h1>{{$author->name}}</h1>
                        {!! $author->description !!}
                    </div>
                </div>
            </div>
        </div>
    </section>
    <section class="category">
        <div class="container">
            <h2 class="subtitle">Шығармалар:</h2>
            <div class="row">
                @foreach($shigarmalar as $item)
                    <div class="col-md-2 col-sm-3">
                        <div class="category-item">
                            <div class="category-item-img">
                                <img src="{{$item->photo}}" alt="">
                                <div class="overlay-play">
                                    <div class="play-info">
                                        <img src="img/icon/play.png" alt="">
                                        <span>{{$item->duration}}</span>
                                    </div>
                                    <a href="/shigarma/{{$item->id}}" class="btn-plain play-lg">
                                        <img src="img/icon/play-lg.png" alt="">
                                    </a>
                                </div>
                            </div>
                            <div class="category-item-caption">
                                <h3>{{$item->name}}</h3>
                                @foreach($item->authors as $item)
                                    <p>{{$item->author_fio}}</p>
                                @endforeach
                            </div>
                        </div>
                    </div>
                @endforeach
            </div>
           {{$shigarmalar->links()}}
        </div>
    </section>
@endsection

resources/views/search.blade.php
@extends('layouts.main')
@section('content')
<section class="category search-box">
    <div class="container">
        <h1><span>Iздеу нәтижесі:</span> {{$search}}</h1>

        <div class="row">
            @foreach($shigarmalar as $item)
                <div class="col-md-2 col-sm-3">
                    <div class="category-item">
                        <div class="category-item-img">
                            <img src="{{$item->photo}}" alt="">
                            <div class="overlay-play">
                                <div class="play-info">
                                    <img src="/img/icon/play.png" alt="">
                                    <span>05:31</span>
                                </div>
                                <a href="/shigarma/{{$item->id}}" class="btn-plain play-lg">
                                    <img src="/img/icon/play-lg.png" alt="">
                                </a>
                            </div>
                        </div>
                        <div class="category-item-caption">
                            <h3>{{$item->name}}</h3>
                            @foreach($item->authors as $item)
                                <p>{{$item->author_fio}}</p>
                            @endforeach
                        </div>
                    </div>
                </div>
            @endforeach
        </div>
        {{ $shigarmalar->links() }}
    </div>
</section>
@endsection

resources/views/shigarma.blade.php
@extends('layouts.main')
@section('style')
    <link rel="stylesheet" href="/css/audioplayer.css">
    <link rel="stylesheet" href="/css/lg-transitions.min.css">
    <link rel="stylesheet" href="/css/lightgallery.min.css">
@endsection
@section('content')
    <section class="category">
        <div class="container">
            <ol class="breadcrumb">
                <li><a href="/">Басты бет</a></li>
                <li><a href="/category/{{$shigarma->rubric["rubric_id"]}}">{{$shigarma->rubric["rubric_name"]}}</a></li>
                <li class="active">{{$shigarma->name}}</li>
            </ol>
            <div class="row">
                <div class="col-md-3 col-sm-4">
                    <div class="inside-img">
                        <img src="{{$shigarma->photo}}" alt="">
                    </div>
                    @if($shigarma->notas)
                    <div class="inside-btn d-flex-justify">
                        <img src="/img/icon/note.png">
                        <p>Нота</p>
                        <button class="btn-plain dynamic"><a target="blank" href="{{($shigarma->notas)?$shigarma->notas["path"]:'#'}}"><img src="/img/icon/arr-white.png" alt=""></a></button>
                    </div>
                    @endif
                </div>
                <div class="col-md-9 col-sm-8">
                    <div class="inside-caption">
                        <h2>{{$shigarma->name}}</h2>
                        {!! $shigarma->description !!}
                        <div class="inside-info">
                            <p>
                                <span>Автор:</span>
                                @foreach($shigarma->authors as $key=>$item)
                                    @if ($key == count($shigarma->authors) - 1)
                                        <a href="/author/{{$item->author_id}}">{{$item->author_fio}}</a>
                                    @else
                                        <a href="/author/{{$item->author_id}}">{{$item->author_fio}}</a> ,
                                    @endif
                                @endforeach
                            </p>
                            <p>
                                <span>Орындаушы:</span>
                                @foreach($shigarma->orindauwilar as $key=>$item)
                                    @if ($key == count($shigarma->orindauwilar) - 1)
                                        <a href="/orindaushi/{{$item->id}}">{{$item->name}}</a>
                                    @else
                                        <a href="/orindaushi/{{$item->id}}">{{$item->name}}</a> ,
                                    @endif
                                @endforeach
                            </p>
                        </div>
                    </div>
                    <div class="audio-box">
                        @foreach($shigarma->orindauwilar as $key=>$item)
                            <div class="audio-cover">
                                <audio preload="auto" controls>
                                    <source src="{{$item->pivot["path"]}}">
                                </audio>

                                <!--<audio src="audio.wav" preload="auto" controls autoplay loop></audio>-->
                                <!--<br type="_moz">-->
                            </div>
                        @endforeach
                    </div>
                </div>
            </div>
        </div>
    </section>
@endsection
@section('script')
    <script src="/js/audioplayer.js"></script>
    <script src="/js/lightgallery.min.js"></script>
    <script src="/js/lightgallery-all.min.js"></script>
    <script type="text/javascript">
        /*$('.dynamic').on('click', function() {

            $(this).lightGallery({
                dynamic: true,
                dynamicEl: [{
                    "src": '/img/main/bobek.png',
                    'thumb': '/img/main/bobek.png',
                    'subHtml': '<h4>Fading Light</h4><p>Classic view from Rigwood Jetty on Coniston Water an old archive shot similar to an old post but a little later on.</p>'
                }, {
                    'src': '/img/main/bobek.png',
                    'thumb': '/img/main/bobek.png',
                    'subHtml': "<h4>Bowness Bay</h4><p>A beautiful Sunrise this morning taken En-route to Keswick not one as planned but I'm extremely happy I was passing the right place at the right time....</p>"
                }, {
                    'src': '/img/main/bobek.png',
                    'thumb': '/img/main/bobek.png',
                    'subHtml': "<h4>Coniston Calmness</h4><p>Beautiful morning</p>"
                }]
            })

        });*/
        //    $('.note').lightGallery();
        $(function() {
            $('audio').audioPlayer();
        });
    </script>
@endsection